/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class active_cache : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal active_cache(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(active_cache obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~active_cache() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SCMPINVOKE.delete_active_cache(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public active_cache() : this(SCMPINVOKE.new_active_cache(), true) {
  }

  public scm_cache cache {
    set {
      SCMPINVOKE.active_cache_cache_set(swigCPtr, scm_cache.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SCMPINVOKE.active_cache_cache_get(swigCPtr);
      scm_cache ret = (cPtr == global::System.IntPtr.Zero) ? null : new scm_cache(cPtr, false);
      return ret;
    } 
  }

  public int uses {
    set {
      SCMPINVOKE.active_cache_uses_set(swigCPtr, value);
    } 
    get {
      int ret = SCMPINVOKE.active_cache_uses_get(swigCPtr);
      return ret;
    } 
  }

}
