/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class active_file : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal active_file(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(active_file obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~active_file() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SCMPINVOKE.delete_active_file(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public active_file() : this(SCMPINVOKE.new_active_file(), true) {
  }

  public scm_file file {
    set {
      SCMPINVOKE.active_file_file_set(swigCPtr, scm_file.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = SCMPINVOKE.active_file_file_get(swigCPtr);
      scm_file ret = (cPtr == global::System.IntPtr.Zero) ? null : new scm_file(cPtr, false);
      return ret;
    } 
  }

  public int uses {
    set {
      SCMPINVOKE.active_file_uses_set(swigCPtr, value);
    } 
    get {
      int ret = SCMPINVOKE.active_file_uses_get(swigCPtr);
      return ret;
    } 
  }

  public int index {
    set {
      SCMPINVOKE.active_file_index_set(swigCPtr, value);
    } 
    get {
      int ret = SCMPINVOKE.active_file_index_get(swigCPtr);
      return ret;
    } 
  }

}
