/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cache_param : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal cache_param(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(cache_param obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~cache_param() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SCMPINVOKE.delete_cache_param(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public cache_param(scm_file file) : this(SCMPINVOKE.new_cache_param(scm_file.getCPtr(file)), true) {
  }

  public int n {
    set {
      SCMPINVOKE.cache_param_n_set(swigCPtr, value);
    } 
    get {
      int ret = SCMPINVOKE.cache_param_n_get(swigCPtr);
      return ret;
    } 
  }

  public int c {
    set {
      SCMPINVOKE.cache_param_c_set(swigCPtr, value);
    } 
    get {
      int ret = SCMPINVOKE.cache_param_c_get(swigCPtr);
      return ret;
    } 
  }

  public int b {
    set {
      SCMPINVOKE.cache_param_b_set(swigCPtr, value);
    } 
    get {
      int ret = SCMPINVOKE.cache_param_b_get(swigCPtr);
      return ret;
    } 
  }

}
