/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum scm_transfb_state {
  TFB_IDLE,
  TFB_CAPTURE_NEXT_FRAME,
  TFB_CAPTURING,
  TFB_PAUSED,
  TFB_COUNT
}
