/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class scm_render : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal scm_render(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(scm_render obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~scm_render() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SCMPINVOKE.delete_scm_render(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public scm_render(int arg0, int arg1) : this(SCMPINVOKE.new_scm_render(arg0, arg1), true) {
  }

  public void render(scm_sphere arg0, scm_scene arg1, scm_scene arg2, SWIGTYPE_p_double arg3, SWIGTYPE_p_double arg4, int arg5, int arg6) {
    SCMPINVOKE.scm_render_render__SWIG_0(swigCPtr, scm_sphere.getCPtr(arg0), scm_scene.getCPtr(arg1), scm_scene.getCPtr(arg2), SWIGTYPE_p_double.getCPtr(arg3), SWIGTYPE_p_double.getCPtr(arg4), arg5, arg6);
  }

  public void render(scm_sphere arg0, scm_scene arg1, scm_scene arg2, scm_scene arg3, scm_scene arg4, SWIGTYPE_p_double arg5, SWIGTYPE_p_double arg6, int arg7, int arg8, double arg9) {
    SCMPINVOKE.scm_render_render__SWIG_1(swigCPtr, scm_sphere.getCPtr(arg0), scm_scene.getCPtr(arg1), scm_scene.getCPtr(arg2), scm_scene.getCPtr(arg3), scm_scene.getCPtr(arg4), SWIGTYPE_p_double.getCPtr(arg5), SWIGTYPE_p_double.getCPtr(arg6), arg7, arg8, arg9);
  }

  public void set_size(int arg0, int arg1) {
    SCMPINVOKE.scm_render_set_size(swigCPtr, arg0, arg1);
  }

  public void set_blur(int arg0) {
    SCMPINVOKE.scm_render_set_blur(swigCPtr, arg0);
  }

  public void set_wire(bool arg0) {
    SCMPINVOKE.scm_render_set_wire(swigCPtr, arg0);
  }

  public int get_blur() {
    int ret = SCMPINVOKE.scm_render_get_blur(swigCPtr);
    return ret;
  }

  public bool get_wire() {
    bool ret = SCMPINVOKE.scm_render_get_wire(swigCPtr);
    return ret;
  }

}
