/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class scm_item : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal scm_item(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(scm_item obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~scm_item() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          SCMPINVOKE.delete_scm_item(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public scm_item() : this(SCMPINVOKE.new_scm_item__SWIG_0(), true) {
  }

  public scm_item(int f, long i) : this(SCMPINVOKE.new_scm_item__SWIG_1(f, i), true) {
  }

  public int f {
    set {
      SCMPINVOKE.scm_item_f_set(swigCPtr, value);
    } 
    get {
      int ret = SCMPINVOKE.scm_item_f_get(swigCPtr);
      return ret;
    } 
  }

  public long i {
    set {
      SCMPINVOKE.scm_item_i_set(swigCPtr, value);
    } 
    get {
      long ret = SCMPINVOKE.scm_item_i_get(swigCPtr);
      return ret;
    } 
  }

  public bool is_valid() {
    bool ret = SCMPINVOKE.scm_item_is_valid(swigCPtr);
    return ret;
  }

}
