/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class SCMPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="SWIGRegisterExceptionCallbacks_SCM")]
    public static extern void SWIGRegisterExceptionCallbacks_SCM(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_SCM")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_SCM(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_SCM(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_SCM(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(SCMPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(SCMPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="SWIGRegisterStringCallback_SCM")]
    public static extern void SWIGRegisterStringCallback_SCM(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_SCM(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static SCMPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_cache")]
  public static extern global::System.IntPtr new_scm_cache(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_cache")]
  public static extern void delete_scm_cache(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_add_load")]
  public static extern void scm_cache_add_load(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_get_page")]
  public static extern int scm_cache_get_page(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, long jarg3, int jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_get_texture")]
  public static extern uint scm_cache_get_texture(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_get_grid_size")]
  public static extern int scm_cache_get_grid_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_get_page_size")]
  public static extern int scm_cache_get_page_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_update")]
  public static extern void scm_cache_update(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_render")]
  public static extern void scm_cache_render(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_flush")]
  public static extern void scm_cache_flush(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_cache_size_set")]
  public static extern void scm_cache_cache_size_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_cache_size_get")]
  public static extern int scm_cache_cache_size_get();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_cache_threads_set")]
  public static extern void scm_cache_cache_threads_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_cache_threads_get")]
  public static extern int scm_cache_cache_threads_get();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_need_queue_size_set")]
  public static extern void scm_cache_need_queue_size_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_need_queue_size_get")]
  public static extern int scm_cache_need_queue_size_get();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_load_queue_size_set")]
  public static extern void scm_cache_load_queue_size_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_load_queue_size_get")]
  public static extern int scm_cache_load_queue_size_get();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_loads_per_cycle_set")]
  public static extern void scm_cache_loads_per_cycle_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_cache_loads_per_cycle_get")]
  public static extern int scm_cache_loads_per_cycle_get();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_file")]
  public static extern global::System.IntPtr new_scm_file(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_file")]
  public static extern void delete_scm_file(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_activate")]
  public static extern void scm_file_activate(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_deactivate")]
  public static extern void scm_file_deactivate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_is_active")]
  public static extern bool scm_file_is_active(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_add_need")]
  public static extern bool scm_file_add_need(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_page_status")]
  public static extern bool scm_file_get_page_status(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_page_offset")]
  public static extern ulong scm_file_get_page_offset(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_page_bounds")]
  public static extern void scm_file_get_page_bounds(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_page_sample")]
  public static extern float scm_file_get_page_sample(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_page_sample4v")]
  public static extern global::System.IntPtr scm_file_get_page_sample4v(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_w")]
  public static extern uint scm_file_get_w(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_h")]
  public static extern uint scm_file_get_h(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_c")]
  public static extern ushort scm_file_get_c(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_b")]
  public static extern ushort scm_file_get_b(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_path")]
  public static extern string scm_file_get_path(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_get_name")]
  public static extern string scm_file_get_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_file_find_page")]
  public static extern ulong scm_file_find_page(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_loader")]
  public static extern int loader(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_load_page")]
  public static extern bool scm_load_page(string jarg1, long jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, ulong jarg4, int jarg5, int jarg6, int jarg7, int jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_toggle_show_indices")]
  public static extern void toggle_show_indices();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_frame")]
  public static extern global::System.IntPtr new_scm_frame(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_frame")]
  public static extern void delete_scm_frame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_frame_bind_frame")]
  public static extern void scm_frame_bind_frame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_frame_bind_color")]
  public static extern void scm_frame_bind_color(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_frame_bind_depth")]
  public static extern void scm_frame_bind_depth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_scm")]
  public static extern string scm_image_get_scm(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_name")]
  public static extern string scm_image_get_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_channel")]
  public static extern int scm_image_get_channel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_normal_min")]
  public static extern float scm_image_get_normal_min(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_normal_max")]
  public static extern float scm_image_get_normal_max(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_set_scm")]
  public static extern void scm_image_set_scm(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_set_name")]
  public static extern void scm_image_set_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_set_channel")]
  public static extern void scm_image_set_channel(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_set_normal_min")]
  public static extern void scm_image_set_normal_min(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_set_normal_max")]
  public static extern void scm_image_set_normal_max(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_is_channel")]
  public static extern bool scm_image_is_channel(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_is_height")]
  public static extern bool scm_image_is_height(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_image")]
  public static extern global::System.IntPtr new_scm_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_image")]
  public static extern void delete_scm_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_init_uniforms")]
  public static extern void scm_image_init_uniforms(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_bind")]
  public static extern void scm_image_bind(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_unbind")]
  public static extern void scm_image_unbind(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_bind_page")]
  public static extern void scm_image_bind_page(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, int jarg3, int jarg4, long jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_unbind_page")]
  public static extern void scm_image_unbind_page(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_touch_page")]
  public static extern void scm_image_touch_page(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, long jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_page_sample")]
  public static extern float scm_image_get_page_sample(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_page_sample4v")]
  public static extern global::System.IntPtr scm_image_get_page_sample4v(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_page_bounds")]
  public static extern void scm_image_get_page_bounds(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_image_get_page_status")]
  public static extern bool scm_image_get_page_status(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_log2")]
  public static extern long log2(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_count")]
  public static extern long scm_page_count(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_level")]
  public static extern long scm_page_level(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_root")]
  public static extern long scm_page_root(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_tile")]
  public static extern long scm_page_tile(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_row")]
  public static extern long scm_page_row(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_col")]
  public static extern long scm_page_col(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_index")]
  public static extern long scm_page_index(long jarg1, long jarg2, long jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_parent")]
  public static extern long scm_page_parent(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_child")]
  public static extern long scm_page_child(long jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_order")]
  public static extern long scm_page_order(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_locate")]
  public static extern void scm_locate(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_vector")]
  public static extern void scm_vector(long jarg1, double jarg2, double jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_north")]
  public static extern long scm_page_north(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_south")]
  public static extern long scm_page_south(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_west")]
  public static extern long scm_page_west(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_east")]
  public static extern long scm_page_east(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_corners")]
  public static extern void scm_page_corners(long jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_center")]
  public static extern void scm_page_center(long jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_page_grid_nv_set")]
  public static extern void page_grid_nv_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_page_grid_nv_get")]
  public static extern int page_grid_nv_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_page_grid_norms_set")]
  public static extern void page_grid_norms_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_page_grid_norms_get")]
  public static extern global::System.IntPtr page_grid_norms_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_page_grid_patchIds_set")]
  public static extern void page_grid_patchIds_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_page_grid_patchIds_get")]
  public static extern global::System.IntPtr page_grid_patchIds_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_page_grid")]
  public static extern global::System.IntPtr new_page_grid();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_page_grid")]
  public static extern void delete_page_grid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_get_grid")]
  public static extern global::System.IntPtr scm_page_get_grid(long jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_get_center")]
  public static extern global::System.IntPtr scm_page_get_center(long jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_item__SWIG_0")]
  public static extern global::System.IntPtr new_scm_item__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_item__SWIG_1")]
  public static extern global::System.IntPtr new_scm_item__SWIG_1(int jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_item_f_set")]
  public static extern void scm_item_f_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_item_f_get")]
  public static extern int scm_item_f_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_item_i_set")]
  public static extern void scm_item_i_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_item_i_get")]
  public static extern long scm_item_i_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_item_is_valid")]
  public static extern bool scm_item_is_valid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_item")]
  public static extern void delete_scm_item(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_label")]
  public static extern global::System.IntPtr new_scm_label(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_label")]
  public static extern void delete_scm_label(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_label_draw")]
  public static extern void scm_label_draw(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, byte jarg3, byte jarg4, byte jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_logopen")]
  public static extern void scm_logopen(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_log")]
  public static extern void scm_log(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_clog")]
  public static extern void scm_clog(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_clognoflush")]
  public static extern void scm_clognoflush(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_logflush")]
  public static extern void scm_logflush();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_logclose")]
  public static extern void scm_logclose();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_path_search")]
  public static extern string scm_path_search(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_render")]
  public static extern global::System.IntPtr new_scm_render(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_render")]
  public static extern void delete_scm_render(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_render_render__SWIG_0")]
  public static extern void scm_render_render__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, int jarg7, int jarg8);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_render_render__SWIG_1")]
  public static extern void scm_render_render__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, int jarg9, int jarg10, double jarg11);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_render_set_size")]
  public static extern void scm_render_set_size(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_render_set_blur")]
  public static extern void scm_render_set_blur(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_render_set_wire")]
  public static extern void scm_render_set_wire(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_render_get_blur")]
  public static extern int scm_render_get_blur(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_render_get_wire")]
  public static extern bool scm_render_get_wire(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_sample")]
  public static extern global::System.IntPtr new_scm_sample(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_sample")]
  public static extern void delete_scm_sample(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sample_get")]
  public static extern float scm_sample_get(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sample_get4v")]
  public static extern global::System.IntPtr scm_sample_get4v(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_scene")]
  public static extern global::System.IntPtr new_scm_scene(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_scene")]
  public static extern void delete_scm_scene(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_color")]
  public static extern uint scm_scene_get_color(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_name")]
  public static extern string scm_scene_get_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_label")]
  public static extern string scm_scene_get_label(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_vert")]
  public static extern string scm_scene_get_vert(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_frag")]
  public static extern string scm_scene_get_frag(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_set_color")]
  public static extern void scm_scene_set_color(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_set_name")]
  public static extern void scm_scene_set_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_set_label")]
  public static extern void scm_scene_set_label(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_set_vert")]
  public static extern void scm_scene_set_vert(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_set_frag")]
  public static extern void scm_scene_set_frag(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_add_image")]
  public static extern int scm_scene_add_image(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_del_image")]
  public static extern void scm_scene_del_image(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_image")]
  public static extern global::System.IntPtr scm_scene_get_image(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_image_count")]
  public static extern int scm_scene_get_image_count(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_init_uniforms")]
  public static extern void scm_scene_init_uniforms(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_draw_label")]
  public static extern void scm_scene_draw_label(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_bind")]
  public static extern void scm_scene_bind(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_unbind")]
  public static extern void scm_scene_unbind(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_bind_page")]
  public static extern void scm_scene_bind_page(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, long jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_unbind_page")]
  public static extern void scm_scene_unbind_page(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_touch_page")]
  public static extern void scm_scene_touch_page(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_minimum_ground")]
  public static extern float scm_scene_get_minimum_ground(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_current_ground")]
  public static extern float scm_scene_get_current_ground(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_page_bounds")]
  public static extern void scm_scene_get_page_bounds(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_page_status")]
  public static extern bool scm_scene_get_page_status(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, long jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_get_program")]
  public static extern uint scm_scene_get_program(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uA_set")]
  public static extern void scm_scene_uA_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uA_get")]
  public static extern global::System.IntPtr scm_scene_uA_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uB_set")]
  public static extern void scm_scene_uB_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uB_get")]
  public static extern global::System.IntPtr scm_scene_uB_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uM_set")]
  public static extern void scm_scene_uM_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uM_get")]
  public static extern int scm_scene_uM_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uzoomv_set")]
  public static extern void scm_scene_uzoomv_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uzoomv_get")]
  public static extern int scm_scene_uzoomv_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uzoomk_set")]
  public static extern void scm_scene_uzoomk_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_scene_uzoomk_get")]
  public static extern int scm_scene_uzoomk_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_page__SWIG_0")]
  public static extern global::System.IntPtr new_scm_page__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_page__SWIG_1")]
  public static extern global::System.IntPtr new_scm_page__SWIG_1(int jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_page__SWIG_2")]
  public static extern global::System.IntPtr new_scm_page__SWIG_2(int jarg1, long jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_page__SWIG_3")]
  public static extern global::System.IntPtr new_scm_page__SWIG_3(int jarg1, long jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_l_set")]
  public static extern void scm_page_l_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_l_get")]
  public static extern int scm_page_l_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_t_set")]
  public static extern void scm_page_t_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_t_get")]
  public static extern int scm_page_t_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_page")]
  public static extern void delete_scm_page(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_set_empty")]
  public static extern bool scm_set_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_set_search")]
  public static extern global::System.IntPtr scm_set_search(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_set_insert")]
  public static extern void scm_set_insert(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_set_remove")]
  public static extern void scm_set_remove(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_set_eject")]
  public static extern global::System.IntPtr scm_set_eject(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, long jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_set")]
  public static extern global::System.IntPtr new_scm_set();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_set")]
  public static extern void delete_scm_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_sphere")]
  public static extern global::System.IntPtr new_scm_sphere(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_sphere")]
  public static extern void delete_scm_sphere(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_prep")]
  public static extern void scm_sphere_prep(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4, int jarg5, int jarg6, bool jarg7);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_draw")]
  public static extern void scm_sphere_draw(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4, int jarg5, int jarg6, int jarg7);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_set_detail")]
  public static extern void scm_sphere_set_detail(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_set_limit")]
  public static extern void scm_sphere_set_limit(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_get_detail")]
  public static extern int scm_sphere_get_detail(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_get_limit")]
  public static extern int scm_sphere_get_limit(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_transfb_set")]
  public static extern void scm_sphere_transfb_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_transfb_get")]
  public static extern global::System.IntPtr scm_sphere_transfb_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_capture_next_frame")]
  public static extern void scm_sphere_capture_next_frame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_ready_to_capture")]
  public static extern int scm_sphere_ready_to_capture(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_set_num_fb_verts")]
  public static extern void scm_sphere_set_num_fb_verts(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_sphere_set_zoom")]
  public static extern void scm_sphere_set_zoom(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, double jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_step__SWIG_0")]
  public static extern global::System.IntPtr new_scm_step__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_step__SWIG_1")]
  public static extern global::System.IntPtr new_scm_step__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_step__SWIG_2")]
  public static extern global::System.IntPtr new_scm_step__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_step__SWIG_3")]
  public static extern global::System.IntPtr new_scm_step__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, double jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_step__SWIG_4")]
  public static extern global::System.IntPtr new_scm_step__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_draw")]
  public static extern void scm_step_draw(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_name")]
  public static extern string scm_step_get_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_foreground")]
  public static extern string scm_step_get_foreground(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_background")]
  public static extern string scm_step_get_background(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_orientation")]
  public static extern void scm_step_get_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_position")]
  public static extern void scm_step_get_position(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_light")]
  public static extern void scm_step_get_light(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_speed")]
  public static extern double scm_step_get_speed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_distance")]
  public static extern double scm_step_get_distance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_tension")]
  public static extern double scm_step_get_tension(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_bias")]
  public static extern double scm_step_get_bias(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_zoom")]
  public static extern double scm_step_get_zoom(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_name")]
  public static extern void scm_step_set_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_foreground")]
  public static extern void scm_step_set_foreground(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_background")]
  public static extern void scm_step_set_background(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_orientation")]
  public static extern void scm_step_set_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_position")]
  public static extern void scm_step_set_position(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_light")]
  public static extern void scm_step_set_light(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_speed")]
  public static extern void scm_step_set_speed(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_distance")]
  public static extern void scm_step_set_distance(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_tension")]
  public static extern void scm_step_set_tension(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_bias")]
  public static extern void scm_step_set_bias(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_zoom")]
  public static extern void scm_step_set_zoom(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_matrix")]
  public static extern void scm_step_get_matrix(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_up")]
  public static extern void scm_step_get_up(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_right")]
  public static extern void scm_step_get_right(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_get_forward")]
  public static extern void scm_step_get_forward(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_pitch")]
  public static extern void scm_step_set_pitch(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_set_matrix")]
  public static extern void scm_step_set_matrix(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_transform_orientation")]
  public static extern void scm_step_transform_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_transform_position")]
  public static extern void scm_step_transform_position(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_step_transform_light")]
  public static extern void scm_step_transform_light(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_step")]
  public static extern void delete_scm_step(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_active_pair__SWIG_0")]
  public static extern global::System.IntPtr new_active_pair__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_active_pair__SWIG_1")]
  public static extern global::System.IntPtr new_active_pair__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_pair_file_set")]
  public static extern void active_pair_file_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_pair_file_get")]
  public static extern global::System.IntPtr active_pair_file_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_pair_cache_set")]
  public static extern void active_pair_cache_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_pair_cache_get")]
  public static extern global::System.IntPtr active_pair_cache_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_active_pair")]
  public static extern void delete_active_pair(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_active_file")]
  public static extern global::System.IntPtr new_active_file();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_file_file_set")]
  public static extern void active_file_file_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_file_file_get")]
  public static extern global::System.IntPtr active_file_file_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_file_uses_set")]
  public static extern void active_file_uses_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_file_uses_get")]
  public static extern int active_file_uses_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_file_index_set")]
  public static extern void active_file_index_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_file_index_get")]
  public static extern int active_file_index_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_active_file")]
  public static extern void delete_active_file(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_active_cache")]
  public static extern global::System.IntPtr new_active_cache();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_cache_cache_set")]
  public static extern void active_cache_cache_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_cache_cache_get")]
  public static extern global::System.IntPtr active_cache_cache_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_cache_uses_set")]
  public static extern void active_cache_uses_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_active_cache_uses_get")]
  public static extern int active_cache_uses_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_active_cache")]
  public static extern void delete_active_cache(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_cache_param")]
  public static extern global::System.IntPtr new_cache_param(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_cache_param_n_set")]
  public static extern void cache_param_n_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_cache_param_n_get")]
  public static extern int cache_param_n_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_cache_param_c_set")]
  public static extern void cache_param_c_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_cache_param_c_get")]
  public static extern int cache_param_c_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_cache_param_b_set")]
  public static extern void cache_param_b_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_cache_param_b_get")]
  public static extern int cache_param_b_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_cache_param")]
  public static extern void delete_cache_param(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_system")]
  public static extern global::System.IntPtr new_scm_system(int jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_system")]
  public static extern void delete_scm_system(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_render_sphere")]
  public static extern void scm_system_render_sphere(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg2, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_flush_cache")]
  public static extern void scm_system_flush_cache(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_render_cache")]
  public static extern void scm_system_render_cache(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_update_cache")]
  public static extern void scm_system_update_cache(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_flush_queue")]
  public static extern void scm_system_flush_queue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_import_queue")]
  public static extern void scm_system_import_queue(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_export_queue")]
  public static extern void scm_system_export_queue(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_append_queue")]
  public static extern void scm_system_append_queue(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_render_queue")]
  public static extern void scm_system_render_queue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_add_scene")]
  public static extern int scm_system_add_scene(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_del_scene")]
  public static extern void scm_system_del_scene(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_scene")]
  public static extern global::System.IntPtr scm_system_get_scene(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_add_step")]
  public static extern int scm_system_add_step(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_del_step")]
  public static extern void scm_system_del_step(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_step")]
  public static extern global::System.IntPtr scm_system_get_step(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_scene_count")]
  public static extern int scm_system_get_scene_count(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_set_scene_blend")]
  public static extern double scm_system_set_scene_blend(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_step_count")]
  public static extern int scm_system_get_step_count(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_step_blend")]
  public static extern global::System.IntPtr scm_system_get_step_blend(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_synchronous")]
  public static extern bool scm_system_get_synchronous(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_set_synchronous")]
  public static extern void scm_system_set_synchronous(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_current_ground")]
  public static extern float scm_system_get_current_ground(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_minimum_ground")]
  public static extern float scm_system_get_minimum_ground(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_sphere")]
  public static extern global::System.IntPtr scm_system_get_sphere(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_render")]
  public static extern global::System.IntPtr scm_system_get_render(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_fore")]
  public static extern global::System.IntPtr scm_system_get_fore(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_back")]
  public static extern global::System.IntPtr scm_system_get_back(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_acquire_scm")]
  public static extern int scm_system_acquire_scm(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_release_scm")]
  public static extern int scm_system_release_scm(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_find_scene")]
  public static extern global::System.IntPtr scm_system_find_scene(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_cache")]
  public static extern global::System.IntPtr scm_system_get_cache(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_file")]
  public static extern global::System.IntPtr scm_system_get_file(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_page_sample")]
  public static extern float scm_system_get_page_sample(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_page_sample4v")]
  public static extern global::System.IntPtr scm_system_get_page_sample4v(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_page_status")]
  public static extern bool scm_system_get_page_status(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, long jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_system_get_page_bounds")]
  public static extern void scm_system_get_page_bounds(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, long jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_task__SWIG_0")]
  public static extern global::System.IntPtr new_scm_task__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_task__SWIG_1")]
  public static extern global::System.IntPtr new_scm_task__SWIG_1(int jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_task__SWIG_2")]
  public static extern global::System.IntPtr new_scm_task__SWIG_2(int jarg1, long jarg2, ulong jarg3, int jarg4, int jarg5, int jarg6, uint jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_make_page")]
  public static extern void scm_task_make_page(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_load_page")]
  public static extern bool scm_task_load_page(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_dump_page")]
  public static extern void scm_task_dump_page(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_o_set")]
  public static extern void scm_task_o_set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_o_get")]
  public static extern ulong scm_task_o_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_n_set")]
  public static extern void scm_task_n_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_n_get")]
  public static extern int scm_task_n_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_c_set")]
  public static extern void scm_task_c_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_c_get")]
  public static extern int scm_task_c_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_b_set")]
  public static extern void scm_task_b_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_b_get")]
  public static extern int scm_task_b_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_u_set")]
  public static extern void scm_task_u_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_u_get")]
  public static extern uint scm_task_u_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_d_set")]
  public static extern void scm_task_d_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_d_get")]
  public static extern bool scm_task_d_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_p_set")]
  public static extern void scm_task_p_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_p_get")]
  public static extern global::System.IntPtr scm_task_p_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_C_set")]
  public static extern void scm_task_C_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_C_get")]
  public static extern global::System.IntPtr scm_task_C_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_task")]
  public static extern void delete_scm_task(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_internal_form")]
  public static extern uint scm_internal_form(ushort jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_external_form")]
  public static extern uint scm_external_form(ushort jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_external_type")]
  public static extern uint scm_external_type(ushort jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_pixel_size")]
  public static extern int scm_pixel_size(ushort jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_sizePerVertex_set")]
  public static extern void scm_transfb_sizePerVertex_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_sizePerVertex_get")]
  public static extern int scm_transfb_sizePerVertex_get();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_vars_set")]
  public static extern void scm_transfb_vars_set(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_vars_get")]
  public static extern global::System.IntPtr scm_transfb_vars_get();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_numVars_set")]
  public static extern void scm_transfb_numVars_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_numVars_get")]
  public static extern int scm_transfb_numVars_get();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_state_set")]
  public static extern void scm_transfb_state_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_state_get")]
  public static extern int scm_transfb_state_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_countVerts_set")]
  public static extern void scm_transfb_countVerts_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_countVerts_get")]
  public static extern int scm_transfb_countVerts_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_scm_transfb")]
  public static extern global::System.IntPtr new_scm_transfb();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_set_num_verts")]
  public static extern void scm_transfb_set_num_verts(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_count_verts")]
  public static extern void scm_transfb_count_verts(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_capture_frame")]
  public static extern void scm_transfb_capture_frame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_will_capture_frame")]
  public static extern int scm_transfb_will_capture_frame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_begin")]
  public static extern void scm_transfb_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_pause")]
  public static extern void scm_transfb_pause(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_resume")]
  public static extern void scm_transfb_resume(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_end")]
  public static extern void scm_transfb_end(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_add_to_count")]
  public static extern void scm_transfb_add_to_count(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_set_size_per_vertex")]
  public static extern void scm_transfb_set_size_per_vertex(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_set_num_vars")]
  public static extern void scm_transfb_set_num_vars(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_set_var")]
  public static extern void scm_transfb_set_var(int jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_num_data")]
  public static extern int scm_transfb_num_data(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_get_data")]
  public static extern global::System.IntPtr scm_transfb_get_data(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_get_data_at")]
  public static extern byte scm_transfb_get_data_at(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_transfb_destroy_data")]
  public static extern void scm_transfb_destroy_data(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_scm_transfb")]
  public static extern void delete_scm_transfb(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_flip")]
  public static extern void image_flip(int jarg1, int jarg2, int jarg3, int jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_read_png")]
  public static extern global::System.IntPtr image_read_png(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_write_png")]
  public static extern void image_write_png(string jarg1, int jarg2, int jarg3, int jarg4, int jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_read_jpg")]
  public static extern global::System.IntPtr image_read_jpg(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_write_jpg")]
  public static extern void image_write_jpg(string jarg1, int jarg2, int jarg3, int jarg4, int jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_read_tif")]
  public static extern global::System.IntPtr image_read_tif(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_write_tif")]
  public static extern void image_write_tif(string jarg1, int jarg2, int jarg3, int jarg4, int jarg5, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]float[] jarg6);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_read_tif_result")]
  public static extern global::System.IntPtr image_read_tif_result(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_read")]
  public static extern global::System.IntPtr image_read(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_write")]
  public static extern void image_write(string jarg1, int jarg2, int jarg3, int jarg4, int jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_read_float")]
  public static extern global::System.IntPtr image_read_float(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_write_float")]
  public static extern void image_write_float(string jarg1, int jarg2, int jarg3, int jarg4, int jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_scale_float")]
  public static extern global::System.IntPtr image_scale_float(int jarg1, int jarg2, int jarg3, int jarg4, int jarg5, global::System.Runtime.InteropServices.HandleRef jarg6);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_internal_form")]
  public static extern int image_internal_form(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_external_form")]
  public static extern int image_external_form(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_image_external_type")]
  public static extern int image_external_type(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_w_set")]
  public static extern void read_tif_results_w_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_w_get")]
  public static extern int read_tif_results_w_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_h_set")]
  public static extern void read_tif_results_h_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_h_get")]
  public static extern int read_tif_results_h_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_c_set")]
  public static extern void read_tif_results_c_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_c_get")]
  public static extern int read_tif_results_c_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_b_set")]
  public static extern void read_tif_results_b_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_b_get")]
  public static extern int read_tif_results_b_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_data_set")]
  public static extern void read_tif_results_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_read_tif_results_data_get")]
  public static extern global::System.IntPtr read_tif_results_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_new_read_tif_results")]
  public static extern global::System.IntPtr new_read_tif_results();

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_delete_read_tif_results")]
  public static extern void delete_read_tif_results(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_page_SWIGUpcast")]
  public static extern global::System.IntPtr scm_page_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("SCM", EntryPoint="CSharp_scm_task_SWIGUpcast")]
  public static extern global::System.IntPtr scm_task_SWIGUpcast(global::System.IntPtr jarg1);
}
